routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('contact', 'WebController@contact')->name('contact');
Route::get('blog/{slug}', 'BlogController@show')->name('blog.slug');
Route::get('checkout', 'CartController@checkout')->name('checkout');
Route::post('agregar-carrito', 'CartController@store')->name('add.cart');
Route::get('shop', 'CartController@shop')->name('shop');
Route::resource('app', 'HomeController');
Route::resource('/', 'WebController');
Route::resource('cart', 'CartController');
Route::resource('blog', 'BlogController');
Route::get('detalles/{slug}', 'WebController@show')->name('product.detail');

Route::resource('posts', 'PostsController');
Route::get('posts/category/index', 'PostsController@indexCategory')->name('posts.category.index');
Route::get('posts/category/create', 'PostsController@createCategory')->name('posts.category.create');
Route::post('posts/category/store', 'PostsController@storeCategory')->name('posts.category.store');
Route::get('posts/category/{id}/edit', 'PostsController@editCategory')->name('posts.category.edit');
Route::patch('posts/category/{id}/update', 'PostsController@updateCategory')->name('posts.category.update');
Route::delete('posts/category/{id}/delete', 'PostsController@deleteCategory')->name('posts.category.delete');

Route::resource('pages', 'PagesController');
Route::resource('products', 'ProductsController');
Route::resource('categories', 'ProductCategoriesController');

Route::resource('slides', 'SlidesController');
Route::resource('stores', 'StoresController');
Route::resource('users', 'UsersController');

Route::resource('messages', 'MessagesController');

app/User.php
<?php

namespace Doz;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace Doz\Http\Controllers;

use Doz\User;
use Illuminate\Http\Request;

use Doz\Http\Requests;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $users = User::paginate(10);

        return view('app.users.index', compact('users'));
    }
}

resources/views/app/users/index.blade.php
@extends('layouts.web')

@section('title', 'Users')

@section('section')

    <section class="container">
        <div class="table-responsive cart_info">
            <table class="table table-condensed">
                <thead>
                <tr class="cart_menu">
                    <td class="image">Imagen</td>
                    <td class="description"></td>
                    <td class="price">Parrafo</td>
                    <td class="quantity">Texto boton</td>
                    <td class="total">Total</td>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td class="cart_product">
                            <a href=""><img src="#" width="150" alt=""></a>
                        </td>

                        <td class="cart_description">
                            <h4><a href="">Titulo 1: </a></h4>
                            <p>Titulo 2: </p>
                        </td>

                        <td class="cart_price">
                            <p></p>
                        </td>

                        <td class="cart_quantity">
                            <div class="cart_quantity_button">

                            </div>
                        </td>

                        <td class="cart_delete">
                            {{--{!! Form::open(['route' => ['slides.destroy', 'id' => $slide->id ], 'method' => 'DELETE']) !!}
                            <button class="btn btn-primary" type="submit"><i class="fa fa-times"></i></button>
                            {!! Form::close() !!}
                            <a href="{{ route('slides.edit', $slide->id) }}" class="btn btn-primary"><i class="fa fa-pencil"></i></>--}}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </section>

@endsection