routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('contact', 'WebController@contact')->name('contact');
Route::get('blog/{slug}', 'BlogController@show')->name('blog.slug');
Route::get('checkout', 'CartController@checkout')->name('checkout');
Route::post('agregar-carrito', 'CartController@store')->name('add.cart');
Route::get('shop', 'CartController@shop')->name('shop');
Route::resource('app', 'HomeController');
Route::resource('/', 'WebController');
Route::resource('cart', 'CartController');
Route::resource('blog', 'BlogController');
Route::get('detalles/{slug}', 'WebController@show')->name('product.detail');

Route::resource('posts', 'PostsController');
Route::get('posts/category/index', 'PostsController@indexCategory')->name('posts.category.index');
Route::get('posts/category/create', 'PostsController@createCategory')->name('posts.category.create');
Route::post('posts/category/store', 'PostsController@storeCategory')->name('posts.category.store');
Route::get('posts/category/{id}/edit', 'PostsController@editCategory')->name('posts.category.edit');
Route::patch('posts/category/{id}/update', 'PostsController@updateCategory')->name('posts.category.update');
Route::delete('posts/category/{id}/delete', 'PostsController@deleteCategory')->name('posts.category.delete');

Route::resource('pages', 'PagesController');
Route::resource('products', 'ProductsController');
Route::resource('categories', 'ProductCategoriesController');

Route::resource('slides', 'SlidesController');
Route::resource('stores', 'StoresController');
Route::resource('users', 'UsersController');

Route::resource('messages', 'MessagesController');

resources/views/layouts/partials/web/brands.blade.php
<div class="brands_products"><!--brands_products-->
    <h2>@lang('web.brands')</h2>
    <div class="brands-name">
        <ul class="nav nav-pills nav-stacked">
            @foreach($brands as $brand)
                <li><a href="#"> <span class="pull-right">(*)</span>{{ $brand->category }}</a></li>
                @endforeach
        </ul>
    </div>
</div><!--/brands_products-->

resources/views/layouts/partials/web/category.blade.php
<div class="panel-group category-products" id="accordian" role="tablist" aria-multiselectable="true"><!--category-productsr-->
    @foreach($categories as $category)
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordian" href="#{{ $category->slug }}">
                        <span class="badge pull-right">
                            <i class="fa fa-plus"></i>
                        </span>
                        {{ $category->category }}
                    </a>
                </h4>
            </div>

            <div id="{{ $category->slug }}" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul>
                        @foreach($category->children as $child)
                            <li>
                                <a href="#">{{ $child->category }}</a>
                            </li>
                            @endforeach
                    </ul>
                </div>
            </div>
        </div>
        @endforeach
</div><!--/category-products-->

resources/views/layouts/partials/web/footer.blade.php
<footer id="footer"><!--Footer-->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="companyinfo">
                        <h2><img src="{{ asset('bower_components/eshopper/images/home/logo.png') }}" alt=""></h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="{{ asset('bower_components/eshopper/images/home/iframe1.png') }}" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="{{ asset('bower_components/eshopper/images/home/iframe2.png') }}" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="{{ asset('bower_components/eshopper/images/home/iframe3.png') }}" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="{{ asset('bower_components/eshopper/images/home/iframe4.png') }}" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="address">
                        <img src="{{ asset('bower_components/eshopper/images/home/map.png') }}" alt="" />
                        <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>@lang('web.service')</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Online Help</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Order Status</a></li>
                            <li><a href="#">Change Location</a></li>
                            <li><a href="#">FAQ’s</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>@lang('web.quick-shop')</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">T-Shirt</a></li>
                            <li><a href="#">Mens</a></li>
                            <li><a href="#">Womens</a></li>
                            <li><a href="#">Gift Cards</a></li>
                            <li><a href="#">Shoes</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>@lang('web.policies')</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Terms of Use</a></li>
                            <li><a href="#">Privecy Policy</a></li>
                            <li><a href="#">Refund Policy</a></li>
                            <li><a href="#">Billing System</a></li>
                            <li><a href="#">Ticket System</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>@lang('web.about-doz')</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Company Information</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Store Location</a></li>
                            <li><a href="#">Affillate Program</a></li>
                            <li><a href="#">Copyright</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3 col-sm-offset-1">
                    <div class="single-widget">
                        <h2>@lang('web.about-doz')</h2>
                        <form action="#" class="searchform">
                            <input type="text" placeholder="Your email address" />
                            <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                            <p>Get the most recent updates from <br />our site and be updated your self...</p>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <p class="pull-left">Copyright © 2016 DOZ S.A.S. @lang('web.all-rights-reserved').</p>
                <!--<p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>-->
            </div>
        </div>
    </div>

</footer><!--/Footer-->

resources/views/layouts/partials/web/header.blade.php
<header id="header"><!--header-->
    <div class="header_top"><!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> 310 7516036</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> ventas@doz.com.co</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <!--<li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>-->
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle"><!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        <a href="{{ route('index') }}">
                            <img src="{{ asset('bower_components/eshopper/images/home/logo.png') }}" alt="" />
                        </a>
                    </div>
                    <!--<div class="btn-group pull-right">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                USA
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canada</a></li>
                                <li><a href="#">UK</a></li>
                            </ul>
                        </div>

                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                DOLLAR
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canadian Dollar</a></li>
                                <li><a href="#">Pound</a></li>
                            </ul>
                        </div>
                    </div>-->
                </div>
                <div class="col-sm-8">
                    <div class="shop-menu pull-right">
                        <ul class="nav navbar-nav">
                            @if(Auth::check())
                            <li><a href="{{ route('app.index') }}"><i class="fa fa-user"></i> @lang('web.account')</a></li>
                                @else
                                @endif
                            <li><a href="#"><i class="fa fa-star"></i> @lang('web.wishlist')</a></li>
                            <li><a href="{{ url('checkout') }}"><i class="fa fa-crosshairs"></i> @lang('web.checkout')</a></li>
                            <li><a href="{{ url('cart') }}"><i class="fa fa-shopping-cart"></i> @lang('web.cart') ({{ Cart::instance('main')->count(false) }})</a></li>
                            @if(Auth::check())
                                <li><a href="{{ route('logout') }}">Cerrar sesion</a></li>
                                @else
                                <li><a href="{{ url('login') }}"><i class="fa fa-lock"></i> @lang('web.login')</a></li>
                                @endif
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li><a href="{{ route('index') }}" class="active">@lang('web.home')</a></li>
                            <li class="dropdown">
                                <a href="{{ route('shop') }}">@lang('web.shop')<!--<i class="fa fa-angle-down"></i>-->
                                </a>
                                <!--<ul role="menu" class="sub-menu">
                                    <li><a href="{{ route('shop') }}">@lang('web.shop')</a></li>
                                    <li><a href="{{ route('checkout') }}">@lang('web.checkout')</a></li>
                                    <li><a href="{{ route('cart.index') }}">@lang('web.cart')</a></li>
                                </ul>-->
                            </li>
                            <li class="dropdown"><a href="#">@lang('web.blog')<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="{{ url('blog') }}">@lang('web.blog')</a></li>
                                    <li><a href="#">@lang('web.blog-post')</a></li>
                                </ul>
                            </li>
                            <li><a href="{{ url('contact') }}">@lang('web.contact')</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="@lang('web.search')"/>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

resources/views/layouts/partials/web/price-range.blade.php
<div class="price-range"><!--price-range-->
    <h2>@lang('web.price-range')</h2>
    <div class="well text-center">
        <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
        <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
    </div>
</div><!--/price-range-->

resources/views/layouts/partials/web/promo.blade.php
<div class="shipping text-center"><!--shipping-->
    <img src="{{ asset('bower_components/eshopper/images/home/shipping.png') }}" alt="" />
</div><!--/shipping-->